# Generated by Django 4.1.5 on 2023-06-14 16:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Pagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pagename",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la página"
                    ),
                ),
                (
                    "pagemetatitle",
                    models.CharField(
                        max_length=200, verbose_name="Metatítulo(title) de la página"
                    ),
                ),
                (
                    "pagetitle",
                    models.CharField(
                        max_length=200, verbose_name="Título(h1) de la página"
                    ),
                ),
                (
                    "pageslogan",
                    models.CharField(
                        max_length=200, verbose_name="Slogan(h2) de la página"
                    ),
                ),
                (
                    "pagemetadesc",
                    models.CharField(
                        max_length=200, verbose_name="Meta descripción de la página"
                    ),
                ),
                (
                    "pagekeywords",
                    ckeditor.fields.RichTextField(
                        verbose_name="Palabras clave de la página"
                    ),
                ),
                (
                    "pageogdesc",
                    models.CharField(
                        max_length=200, verbose_name="Descripción OG de la página"
                    ),
                ),
                (
                    "pageogtitle",
                    models.CharField(
                        max_length=200, verbose_name="Título OG de la página"
                    ),
                ),
                (
                    "pageogurl",
                    models.CharField(
                        max_length=200, verbose_name="Url OG de la página"
                    ),
                ),
                (
                    "pageogimg",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Microformato de la página"
                    ),
                ),
                (
                    "pageogurlsec",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Segura de la página"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "videoname",
                    models.CharField(max_length=200, verbose_name="Nombre del video"),
                ),
                (
                    "videourl",
                    models.CharField(max_length=200, verbose_name="URL del video"),
                ),
            ],
        ),
    ]
