# Generated by Django 4.1.5 on 2023-06-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagina",
            name="pagebanner",
            field=models.ImageField(
                default="/productos/static/img/default.jpg",
                upload_to="imagenes-decortinas/",
                verbose_name="Imagen Banner de la página",
            ),
        ),
        migrations.AddField(
            model_name="pagina",
            name="pagebannermov",
            field=models.ImageField(
                default="/productos/static/img/default-mov.jpg",
                upload_to="imagenes-decortinas/",
                verbose_name="Imagen Banner de la página en Móvil",
            ),
        ),
    ]
