# Generated by Django 4.1.5 on 2023-07-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_pagina_pagebanner_pagina_pagebannermov"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagina",
            name="pagebanner",
            field=models.ImageField(
                default="/productos/static/img/default.jpg",
                upload_to="teacompano-img/",
                verbose_name="Imagen Banner de la página",
            ),
        ),
        migrations.AlterField(
            model_name="pagina",
            name="pagebannermov",
            field=models.ImageField(
                default="/productos/static/img/default-mov.jpg",
                upload_to="teacompano-img/",
                verbose_name="Imagen Banner de la página en Móvil",
            ),
        ),
    ]
