# Generated by Django 4.1.5 on 2023-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_pagina_pagemetadesc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="/productos/static/img/default.jpg",
                        upload_to="teacompano-img/",
                        verbose_name="Imagen de la página",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="pagina",
            name="pagebanner",
        ),
        migrations.AddField(
            model_name="pagina",
            name="pagebanner",
            field=models.ManyToManyField(
                related_name="paginas",
                to="web.imagen",
                verbose_name="Imagenes Banner de la página",
            ),
        ),
    ]
