# Generated by Django 4.1.5 on 2023-07-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_imagen_remove_pagina_pagebanner_pagina_pagebanner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagina",
            name="pagebanner",
        ),
        migrations.DeleteModel(
            name="Imagen",
        ),
        migrations.AddField(
            model_name="pagina",
            name="pagebanner",
            field=models.ImageField(
                default="/productos/static/img/default.jpg",
                upload_to="teacompano-img/",
                verbose_name="Imagen Banner de la página",
            ),
        ),
    ]
