# Generated by Django 4.1.5 on 2023-07-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_remove_pagina_pagebanner_delete_imagen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagina",
            name="pageogdesc",
        ),
        migrations.RemoveField(
            model_name="pagina",
            name="pageogtitle",
        ),
    ]
