# Generated by Django 4.1.5 on 2023-07-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_remove_pagina_pageogdesc_remove_pagina_pageogtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagina",
            name="pageogdesc",
            field=models.CharField(
                default="Descripción del sitio web",
                max_length=400,
                verbose_name="Descripción OG de la página",
            ),
        ),
    ]
