# Generated by Django 4.1.5 on 2023-07-27 15:46

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_pagina_pageogdesc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del usuario"),
                ),
                (
                    "correo",
                    models.EmailField(max_length=254, verbose_name="Email del usuario"),
                ),
                ("celular", models.CharField(max_length=15)),
                (
                    "descripcion",
                    ckeditor.fields.RichTextField(
                        verbose_name="Descripción del paciente"
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
