# Generated by Django 4.1.5 on 2023-07-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_alter_formulario_celular_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="servicio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Enfermería", "Enfermeria"),
                    ("Consulta Médica", "Consulta Médica"),
                    ("Consulta Psicología", "Consulta Psicología"),
                    ("Fisioterapia", "Terapia Física"),
                    ("Consulta Jurídica", "Consulta Jurídica"),
                ],
                max_length=200,
                verbose_name="Servicio solicitado",
            ),
        ),
    ]
