# Generated by Django 4.1.5 on 2023-08-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_formulario_servicio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kardex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paciente",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre del paciente"
                    ),
                ),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Diagnóstico"
                    ),
                ),
                (
                    "dieta",
                    models.CharField(blank=True, max_length=200, verbose_name="Dieta"),
                ),
                (
                    "edad",
                    models.CharField(blank=True, max_length=200, verbose_name="Edad"),
                ),
                (
                    "peso",
                    models.CharField(blank=True, max_length=200, verbose_name="Peso"),
                ),
                (
                    "tratamiento",
                    models.TextField(
                        blank=True, verbose_name="Tratamiento Farmacológico"
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        blank=True, verbose_name="Plan de cuidados de enfermería"
                    ),
                ),
            ],
        ),
    ]
