# Generated by Django 4.1.5 on 2023-08-14 19:10

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_kardex"),
    ]

    operations = [
        migrations.AddField(
            model_name="kardex",
            name="fecha_kardex",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="kardex",
            name="plan",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Plan de cuidados de enfermería"
            ),
        ),
        migrations.AlterField(
            model_name="kardex",
            name="tratamiento",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Tratamiento Farmacológico"
            ),
        ),
    ]
