# Generated by Django 4.1.5 on 2023-08-17 20:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_kardex_fecha_kardex_alter_kardex_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagina",
            name="pagebanner",
            field=models.ImageField(
                default="/Servicios/static/img/default.jpg",
                upload_to="teacompano-img/",
                verbose_name="Imagen Banner de la página",
            ),
        ),
        migrations.AlterField(
            model_name="pagina",
            name="pagebannermov",
            field=models.ImageField(
                default="/Servicios/static/img/default-mov.jpg",
                upload_to="teacompano-img/",
                verbose_name="Imagen Banner de la página en Móvil",
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servicename",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Servicio"
                    ),
                ),
                (
                    "serviceslogan",
                    models.CharField(
                        max_length=200, verbose_name="Slogan del Servicio"
                    ),
                ),
                (
                    "servicemetadesc",
                    models.CharField(
                        max_length=200, verbose_name="Meta descripción del Servicio"
                    ),
                ),
                (
                    "servicekeywords",
                    ckeditor.fields.RichTextField(
                        verbose_name="Palabras clave del Servicio"
                    ),
                ),
                (
                    "servicebanner",
                    models.ImageField(
                        default="/Servicios/static/img/default.jpg",
                        upload_to="teacompano-img/",
                        verbose_name="Imagen Banner del Servicio",
                    ),
                ),
                (
                    "servicebannermov",
                    models.ImageField(
                        default="/Servicios/static/img/default-mov.jpg",
                        upload_to="teacompano-img/",
                        verbose_name="Imagen Banner del Servicio en Móvil",
                    ),
                ),
                (
                    "serviceogdesc",
                    models.CharField(
                        max_length=200, verbose_name="Descripción OG del Servicio"
                    ),
                ),
                (
                    "serviceogtitle",
                    models.CharField(
                        max_length=200, verbose_name="Metatítulo OG del Servicio"
                    ),
                ),
                (
                    "serviceogurl",
                    models.CharField(
                        max_length=200, verbose_name="Url OG del Servicio"
                    ),
                ),
                (
                    "serviceogimg",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Microformato del Servicio"
                    ),
                ),
                (
                    "serviceogurlsec",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Segura del Servicio"
                    ),
                ),
                (
                    "serviceurl",
                    models.CharField(
                        max_length=200, verbose_name="Url Servicio detalle"
                    ),
                ),
                ("servicedescription", ckeditor.fields.RichTextField()),
                (
                    "serviceimg",
                    models.ImageField(
                        upload_to="teacompano-img/",
                        verbose_name="Imagen principal del Servicio",
                    ),
                ),
                (
                    "gallerya",
                    models.ImageField(
                        blank=True,
                        upload_to="teacompano-img/",
                        verbose_name="Imagen secundaria del Servicio",
                    ),
                ),
                (
                    "galleryb",
                    models.ImageField(
                        blank=True,
                        upload_to="teacompano-img/",
                        verbose_name="Imagen adicional del Servicio",
                    ),
                ),
                (
                    "galleryc",
                    models.ImageField(
                        blank=True,
                        upload_to="teacompano-img/",
                        verbose_name="Imagen final del Servicio",
                    ),
                ),
                ("serviceupdated", models.DateTimeField(auto_now=True)),
                (
                    "asesor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.asesor",
                    ),
                ),
            ],
        ),
    ]
