# Generated by Django 4.1.5 on 2023-08-17 20:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_alter_pagina_pagebanner_alter_pagina_pagebannermov_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="servicemetadesc",
            field=ckeditor.fields.RichTextField(
                verbose_name="Meta descripción del Servicio"
            ),
        ),
    ]
