# Generated by Django 4.1.5 on 2023-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_alter_service_servicemetadesc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="servicemetadesc",
            field=models.CharField(
                max_length=300, verbose_name="Meta descripción del Servicio"
            ),
        ),
    ]
