# Generated by Django 4.1.5 on 2023-08-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_alter_service_servicemetadesc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="serviceogtitle",
        ),
    ]
