# Generated by Django 4.1.5 on 2023-08-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_remove_service_serviceogdesc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="serviceogdesc",
            field=models.CharField(
                default="Descripción del servicio",
                max_length=400,
                verbose_name="Descripción OG del servicio",
            ),
        ),
    ]
