# Generated by Django 4.1.5 on 2023-09-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_service_servicesnipeta_service_servicesnipetb_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Galeria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador", models.CharField(max_length=200)),
                ("imagen", models.ImageField(upload_to="teacompano-img/")),
            ],
        ),
    ]
