# Generated by Django 4.1.5 on 2023-09-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_galeria"),
    ]

    operations = [
        migrations.AddField(
            model_name="kardex",
            name="oxigeno",
            field=models.CharField(blank=True, max_length=200, verbose_name="Oxigeno"),
        ),
    ]
