# Generated by Django 4.2.5 on 2023-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_kardex_oxigeno"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenesPrincipales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imgname",
                    models.CharField(
                        max_length=200, verbose_name="Identificador de la imagen"
                    ),
                ),
                (
                    "imagenp",
                    models.ImageField(
                        default="/servicios/static/img/banner-ejemplo-b.jpg",
                        upload_to="teacompano-img/",
                        verbose_name="Imagen principal",
                    ),
                ),
                (
                    "imagenalt",
                    models.CharField(max_length=200, verbose_name="Alt de la imagen"),
                ),
                (
                    "imgslogan",
                    models.CharField(max_length=30, verbose_name="Slogan de la imagen"),
                ),
                (
                    "imgtitle",
                    models.CharField(max_length=10, verbose_name="Titulo de la imagen"),
                ),
                (
                    "imgcta",
                    models.CharField(max_length=200, verbose_name="Call to action"),
                ),
                (
                    "imglink",
                    models.CharField(max_length=200, verbose_name="Enlace CTA"),
                ),
            ],
        ),
    ]
