# Generated by Django 4.2.5 on 2023-09-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_imagenesprincipales_imgasesor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagenesprincipales",
            name="imagenalt",
            field=models.CharField(
                blank="true", max_length=200, verbose_name="Alt de la imagen"
            ),
        ),
        migrations.AlterField(
            model_name="imagenesprincipales",
            name="imgcta",
            field=models.CharField(
                blank="true", max_length=200, verbose_name="Call to action"
            ),
        ),
        migrations.AlterField(
            model_name="imagenesprincipales",
            name="imglink",
            field=models.CharField(
                blank="true", max_length=200, verbose_name="Enlace CTA"
            ),
        ),
        migrations.AlterField(
            model_name="imagenesprincipales",
            name="imgslogan",
            field=models.CharField(
                blank="true", max_length=30, verbose_name="Slogan de la imagen"
            ),
        ),
        migrations.AlterField(
            model_name="imagenesprincipales",
            name="imgtitle",
            field=models.CharField(
                blank="true", max_length=10, verbose_name="Titulo de la imagen"
            ),
        ),
    ]
