# Generated by Django 4.2.5 on 2023-09-26 15:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0026_alter_imagenesprincipales_imagenalt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagenesprincipales",
            name="imgslogan",
            field=ckeditor.fields.RichTextField(
                blank="true", verbose_name="Slogan de la Imagen"
            ),
        ),
        migrations.AlterField(
            model_name="imagenesprincipales",
            name="imgtitle",
            field=ckeditor.fields.RichTextField(
                blank="true", verbose_name="Titulo de la Imagen"
            ),
        ),
    ]
